stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test

build-image:
  before-script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build

deploy:
  stage: deploy
  script:
    - ./deploy.sh
  only:
    - master
  image:
